name: cooccurrence-scan
on:
  schedule:
    - cron: "15 8 * * 2,5"   # Tue/Fri
  workflow_dispatch:

jobs:
  cooccur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r CORE/requirements.txt
      - name: Run co-occurrence scan
        run: |
          python CORE/cooccur/scan.py
      - name: Commit co-occurrence graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "cooccurrence: updated graph" || echo "no changes"
          git push
