name: weekly-ingest
on:
  schedule:
    - cron: "0 7 * * 1"   # Mondays 07:00 UTC
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r CORE/requirements.txt

      - name: Initialize DB (if needed)
        run: |
          python - <<'PY'
          import sqlite3, os
          os.makedirs('data/processed', exist_ok=True)
          conn = sqlite3.connect('data/processed/records.sqlite')
          conn.executescript(open('CORE/schema.sql').read())
          conn.commit(); conn.close()
          print('DB initialized')
          PY

      - name: Ingest seeds
        run: |
          python CORE/ingest_pipeline/url_list_ingest.py \
            --subject "Donald J. Trump" \
            --topic_cluster general \
            --urls seeds/sources.urls.txt

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "weekly: ingest updates" || echo "no changes"
          git push
